# This is a basic workflow to help you get started with Actions

name: Standardrb

# Controls when the action will run.
on:
  pull_request:
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      BUNDLE_DEPLOYMENT: false
      BUNDLE_FROZEN: false
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      # Disabled for now because of an issue installing ruby-debug-ide
      # with:
      #   bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: |
          bundle install
          bundle exec standardrb
